// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sdk_bridge.djinni

#import "Muse/gen-objc/IXNCharacteristicId.h"
#import <Foundation/Foundation.h>
@class IXNCharacteristicMapper;


@interface IXNCharacteristicMapper : NSObject

+ (nullable IXNCharacteristicMapper *)instance;

- (nonnull NSData *)uuidForCharacteristic:(IXNCharacteristicId)characteristic;

- (IXNCharacteristicId)characteristicForUuid:(nonnull NSData *)uuid;

- (nonnull NSArray *)allCharacteristicUuids;

@end
