// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sdk_bridge.djinni

#import <Foundation/Foundation.h>


@protocol IXNConnectionHandle

/** Returns true if the Bluetooth socket has incoming data. */
- (BOOL)hasBytes;

/**
 * Returns data from the Bluetooth socket.
 * Returns an empty array if there is no data.
 */
- (nonnull NSData *)getBytes;

/**
 * Sends data to the remove device through the Bluetooth socket.
 * param data - data to send
 */
- (void)writeBytes:(nonnull NSString *)toWrite;

/** Sends raw binary data to the remote device. */
- (void)writeBinaryBytes:(nonnull NSData *)toWrite;

@end
