// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * Represents the data mapping in a DRL_REF packet.
 * \if ANDROID_ONLY
 * \sa com.choosemuse.libmuse.MuseDataPacketType.DRL_REF
 * \sa com.choosemuse.libmuse.MuseDataPacket.getDrlRefValue()
 * \endif
 * \if IOS_ONLY
 * sa \link IXNMuseDataPacketType::IXNMuseDataPacketTypeDrlRef IXNMuseDataPacketTypeDrlRef\endlink
 * \sa IXNMuseDataPacket::getDrlRefValue:
 * \endif
 */
typedef NS_ENUM(NSInteger, IXNDrlRef)
{
    /** DRL sensor */
    IXNDrlRefDrl,
    /** REF sensor */
    IXNDrlRefRef,
};
