// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sdk_bridge.djinni

#import <Foundation/Foundation.h>

/**
 * Advertised information about a device.
 *
 * These values are available prior to connection, and can be used to decide
 * which devices are available to connect to.
 */
@interface IXNDeviceInformation : NSObject
- (nonnull id)initWithName:(nonnull NSString *)name
                identifier:(nonnull NSString *)identifier
                      rssi:(double)rssi
        lastDiscoveredTime:(double)lastDiscoveredTime;

/** A human-readable name for this device. */
@property (nonatomic, readonly, nonnull) NSString * name;

/**
 * This value is platform-specific. On iOS, it is the UUID provided by
 * CoreBluetooth.  On Android, it is the MAC address.
 * \if WINDOWS_ONLY
 * On Windows, it is the MAC address.
 * \endif
 */
@property (nonatomic, readonly, nonnull) NSString * identifier;

/** Device signal strength reported by the OS, in decibels. */
@property (nonatomic, readonly) double rssi;

/**
 * Time at which this device was most recently discovered.
 *
 * This value is in microseconds since some common start time (e.g. unix
 * epoch, device start time, or app start time). It should not be used to
 * record absolute times, but only compared with times from other devices to
 * determine which was discovered most recently.
 *
 * \if IOS_ONLY
 * This value is equivalent to CACurrentMediaTime() converted to microseconds.
 * \endif
 */
@property (nonatomic, readonly) double lastDiscoveredTime;

@end
