// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from packets.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * Represents the data mapping in a EEG packet and in a
 * Quantization packet.
 * Enum values correspond to head locations. Check
 * http://developer.choosemuse.com/hardware-firmware/hardware-specifications
 * for details.
 * \if ANDROID_ONLY
 * \sa com.choosemuse.libmuse.MuseDataPacketType.EEG
 * \sa com.choosemuse.libmuse.MuseDataPacket.getEegChannelValue()
 * \endif
 * \if IOS_ONLY
 * sa \link IXNMuseDataPacketType::IXNMuseDataPacketTypeEeg IXNMuseDataPacketTypeEeg\endlink
 * \sa IXNMuseDataPacket::getEegChannelValue:
 * \endif
 */
typedef NS_ENUM(NSInteger, IXNEeg)
{
    /** Left ear */
    IXNEegEEG1,
    /** Left forehead */
    IXNEegEEG2,
    /** Right forehead */
    IXNEegEEG3,
    /** Right ear */
    IXNEegEEG4,
    /** Left auxiliary. */
    IXNEegAUXLEFT,
    /** Right auxiliary. */
    IXNEegAUXRIGHT,
};
