// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sdk_bridge.djinni

#import <Foundation/Foundation.h>
@class IXNMuse;
@protocol IXNEventLoop;
@protocol IXNMuseLeDevice;

/** Factory that produces a Muse given a Bluetooth low-energy device. */

@interface IXNMuseLeFactory : NSObject

+ (nullable IXNMuse *)getMuse:(nullable id<IXNMuseLeDevice>)device
                    asyncLoop:(nullable id<IXNEventLoop>)asyncLoop;

@end
