// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from sdk_bridge.djinni

#import "Muse/gen-objc/IXNCharacteristicId.h"
#import <Foundation/Foundation.h>

/**
 * This is the platform-independent side of Bluetooth low-energy connections.
 *
 * Each instance of this class should be the delegate of a muse_le_device. The
 * muse_le_device will call the appropriate methods on its delegate every time
 * their corresponding events occur.
 */

@interface IXNMuseLeDeviceDelegate : NSObject

/** A connection request completed successfully. */
- (void)didConnect;

/** A connection request failed, or an existing connection ended. */
- (void)didDisconnect;

/**
 * A request to start receiving characteristic updates completed.
 *
 * Note that characteristic values may start arriving before this is called,
 * e.g. if some requests to enable notifications completed before others.
 * The purpose of this call is not to mark the actual start of
 * characteristic updates, but rather to mark the point after which it is
 * safe to call request_stop_receiving on the device.
 */
- (void)didStartReceiving;

/** A request to stop receiving characteristic updates completed. */
- (void)didStopReceiving;

/** A new packet was received for the given characteristic. */
- (void)didReceiveValueForCharacteristic:(IXNCharacteristicId)characteristic
                                   value:(nonnull NSData *)value;

@end
