// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from museinfo.djinni

#import <Foundation/Foundation.h>

/**
 * \if IOS_ONLY
 * \file
 * \endif
 * Defines all possible Muse presets. See this link for details:
 * http://developer.choosemuse.com/hardware-firmware/headband-configuration-presets
 * <br>
 *
 * Presets are specific to the model of headband.  For example, setting a preset
 * that is intended for %Muse 2014 (
 * \if ANDROID_ONLY
 * \link com.choosemuse.libmuse.MuseModel.MU_01 MU_01\endlink
 * \elseif IOS_ONLY
 * \link ::IXNMuseModel::IXNMuseModelMu01 MU_01\endlink
 * \endif
 * ) headband on a %Muse 2016 (
 * \if ANDROID_ONLY
 * \link com.choosemuse.libmuse.MuseModel.MU_02 MU_02\endlink
 * \elseif IOS_ONLY
 * \link ::IXNMuseModel::IXNMuseModelMu02 MU_02\endlink
 * \endif
 * ) headband will not work.  Attempting to set an incorrect preset on a headband will result
 * in a warning in the log and the incorrect preset will be ignored.  To avoid this, you should
 * first connect to the headband without setting a preset and check the
 * \if ANDROID_ONLY
 * MuseConfiguration
 * \elseif IOS_ONLY
 * IXNMuseConfiguration
 * \endif
 * to get the model of the headband and then set the appropriate preset.
 * You can also obtain the current preset of the headband from the
 * \if ANDROID_ONLY
 * MuseConfiguration
 * \elseif IOS_ONLY
 * IXNMuseConfiguration
 * \endif
 * <br>
 *
 * If you change the preset to while the headband is connected, the headband will disconnect.
 * If the preset is valid for that headband model, then the headband will automatically reconnect.
 * If the preset is invalid for that headband model, then the headband will remain disconnected.
 *
 * \sa
 * \if ANDROID_ONLY
 * MuseConfiguration
 * \elseif IOS_ONLY
 * IXNMuseConfiguration
 * \endif
 */
typedef NS_ENUM(NSInteger, IXNMusePreset)
{
    /**
     * 4 CH, 10 bit @ 220 sps, compression ON, no accelerometer, no battery
     * data, no error data, no DRL/REF data.
     * <br>
     *
     * Availability: %Muse 2014 (
     * \if ANDROID_ONLY
     * \link com.choosemuse.libmuse.MuseModel.MU_01 MU_01\endlink
     * \elseif IOS_ONLY
     * \link ::IXNMuseModel::IXNMuseModelMu01 MU_01\endlink
     * \endif
     * ) only
     */
    IXNMusePresetPreset10,
    /**
     * 4 CH, 10 bit @ 220 sps, compression ON, 50 sps accelerometer data,
     * 0.1 sps battery data, no error data, no DRL/REF data
     * <br>
     *
     * Availability: %Muse 2014 (
     * \if ANDROID_ONLY
     * \link com.choosemuse.libmuse.MuseModel.MU_01 MU_01\endlink
     * \elseif IOS_ONLY
     * \link ::IXNMuseModel::IXNMuseModelMu01 MU_01\endlink
     * \endif
     * ) only
     */
    IXNMusePresetPreset12,
    /**
     * 4 CH, 10 bit @ 220 sps, compression ON, 50 sps accelerometer data,
     * 0.1 sps battery data, real-time error data, 10 bit @ 10 sps DRL/REF data
     * <br>
     *
     * This is the default for
     * %Muse 2014 (
     * \if ANDROID_ONLY
     * \link com.choosemuse.libmuse.MuseModel.MU_01 MU_01\endlink
     * \elseif IOS_ONLY
     * \link ::IXNMuseModel::IXNMuseModelMu01 MU_01\endlink
     * \endif
     * ).
     * <br>
     *
     * Availability: %Muse 2014 (
     * \if ANDROID_ONLY
     * \link com.choosemuse.libmuse.MuseModel.MU_01 MU_01\endlink
     * \elseif IOS_ONLY
     * \link ::IXNMuseModel::IXNMuseModelMu01 MU_01\endlink
     * \endif
     * ) only
     */
    IXNMusePresetPreset14,
    /**
     * 5 CH, 12 bit @ 256 sps, 52 sps accelerometer/gyro, 0.1 sps battery,
     * 32 sps DRL/REF.
     * <br>
     *
     * Availability: %Muse 2016 (
     * \if ANDROID_ONLY
     * \link com.choosemuse.libmuse.MuseModel.MU_02 MU_02\endlink
     * \elseif IOS_ONLY
     * \link ::IXNMuseModel::IXNMuseModelMu02 MU_02\endlink
     * \endif
     * ) only
     */
    IXNMusePresetPreset20,
    /**
     * 4 CH, 12 bit @ 256 sps, 52 sps accelerometer/gyro, 0.1 sps battery,
     * 32 sps DRL/REF.
     * <br>
     *
     * This is the default for
     * %Muse 2016 (
     * \if ANDROID_ONLY
     * \link com.choosemuse.libmuse.MuseModel.MU_02 MU_02\endlink
     * \elseif IOS_ONLY
     * \link ::IXNMuseModel::IXNMuseModelMu02 MU_02\endlink
     * \endif
     * ) only
     * <br>
     *
     * Availability: %Muse 2016 (
     * \if ANDROID_ONLY
     * \link com.choosemuse.libmuse.MuseModel.MU_02 MU_02\endlink
     * \elseif IOS_ONLY
     * \link ::IXNMuseModel::IXNMuseModelMu02 MU_02\endlink
     * \endif
     * ) only
     */
    IXNMusePresetPreset21,
    /**
     * 4 CH, 12 bit @ 256 sps, 0.1 sps battery,
     * 32 sps DRL/REF.
     * <br>
     *
     * Availability: %Muse 2016 (
     * \if ANDROID_ONLY
     * \link com.choosemuse.libmuse.MuseModel.MU_02 MU_02\endlink
     * \elseif IOS_ONLY
     * \link ::IXNMuseModel::IXNMuseModelMu02 MU_02\endlink
     * \endif
     * ) only
     */
    IXNMusePresetPreset22,
    /**
     * 6 CH. Factory usage only.  Commercial headbands do not support this preset.
     * <br>
     *
     * Availability: %Muse 2016 (
     * \if ANDROID_ONLY
     * \link com.choosemuse.libmuse.MuseModel.MU_02 MU_02\endlink
     * \elseif IOS_ONLY
     * \link ::IXNMuseModel::IXNMuseModelMu02 MU_02\endlink
     * \endif
     * ) only
     */
    IXNMusePresetPreset23,
    /**
     * 6 CH, 16 bit @ 500 sps, 50 sps accelerometer, 0.1 sps battery,
     * compression OFF, notch filter OFF, no error data, no DRL/REF data
     * <br>
     *
     * Research preset:<br>
     * Only the following data packets are generated with this preset:
     * \if ANDROID_ONLY
     * \link com.choosemuse.libmuse.MuseDataPacketType.EEG EEG\endlink,
     * \link com.choosemuse.libmuse.MuseDataPacketType.ACCELEROMETER ACCELEROMETER\endlink,
     * \link com.choosemuse.libmuse.MuseDataPacketType.BATTERY BATTERY\endlink
     * \elseif IOS_ONLY
     * \link ::IXNMuseDataPacketType::IXNMuseDataPacketTypeEeg IXNMuseDataPacketTypeEeg\endlink,
     * \link ::IXNMuseDataPacketType::IXNMuseDataPacketTypeAccelerometer IXNMuseDataPacketTypeAccelerometer\endlink,
     * \link ::IXNMuseDataPacketType::IXNMuseDataPacketTypeBattery IXNMuseDataPacketTypeBattery\endlink
     * \endif
     * <br>
     * Artifacts are not generated with this preset.<br>
     *
     * Availability: %Muse 2014 (
     * \if ANDROID_ONLY
     * \link com.choosemuse.libmuse.MuseModel.MU_01 MU_01\endlink
     * \elseif IOS_ONLY
     * \link ::IXNMuseModel::IXNMuseModelMu01 MU_01\endlink
     * \endif
     * ) only
     */
    IXNMusePresetPresetAb,
    /**
     * 4 CH, 16 bit @ 500 sps, 50 sps accelerometer, 0.1 sps battery,
     * compression OFF, notch filter OFF, no error data, no DRL/REF data
     * <br>
     *
     * Research preset:<br>
     * Only the following data packets are generated with this preset:
     * \if ANDROID_ONLY
     * \link com.choosemuse.libmuse.MuseDataPacketType.EEG EEG\endlink,
     * \link com.choosemuse.libmuse.MuseDataPacketType.ACCELEROMETER ACCELEROMETER\endlink,
     * \link com.choosemuse.libmuse.MuseDataPacketType.BATTERY BATTERY\endlink
     * \elseif IOS_ONLY
     * \link ::IXNMuseDataPacketType::IXNMuseDataPacketTypeEeg IXNMuseDataPacketTypeEeg\endlink,
     * \link ::IXNMuseDataPacketType::IXNMuseDataPacketTypeAccelerometer IXNMuseDataPacketTypeAccelerometer\endlink,
     * \link ::IXNMuseDataPacketType::IXNMuseDataPacketTypeBattery IXNMuseDataPacketTypeBattery\endlink
     * \endif
     * <br>
     * Artifacts are not generated with this preset.<br>
     *
     * Availability: %Muse 2014 (
     * \if ANDROID_ONLY
     * \link com.choosemuse.libmuse.MuseModel.MU_01 MU_01\endlink
     * \elseif IOS_ONLY
     * \link ::IXNMuseModel::IXNMuseModelMu01 MU_01\endlink
     * \endif
     * ) only
     */
    IXNMusePresetPresetAd,
};
