// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from listeners.djinni

#import "Muse/gen-objc/IXNAnnotationData.h"
#import "Muse/gen-objc/IXNComputingDeviceConfiguration.h"
#import <Foundation/Foundation.h>
@class IXNMuseConfiguration;
@class IXNMuseVersion;

/**
 * Implement this interface to receive annotations and configuration/version
 * info from a
 * \if ANDROID_ONLY
 * ReaderMuse.
 * \elseif IOS_ONLY
 * IXNReaderMuse
 * \endif
 */

@protocol IXNReaderListener

/**
 * Called once for each annotation in the file.
 * \param annotation The annotation data that was read.
 */
- (void)receiveAnnotation:(nonnull IXNAnnotationData *)annotation;

/**
 * Called each time a version packet is encountered.
 * \param version The version data that was read.
 */
- (void)receiveVersion:(nullable IXNMuseVersion *)version;

/**
 * Called each time a configuration packet is encountered.
 * \param configuration The configuration data that was read.
 */
- (void)receiveConfiguration:(nullable IXNMuseConfiguration *)configuration;

/**
 * Called each time a computing device packet is encountered.
 * \param computingDeviceConfiguration The device configuration that was read.
 */
- (void)receiveComputingDeviceConfiguration:(nonnull IXNComputingDeviceConfiguration *)computingDeviceConfiguration;

@end
